### ISSUE TITLE
Allow connection to any version of the tenforce/virtuoso images

### ISSUE THREAD

**Issue by white-gecko** [Dockerizing/virtuoso-import-docker#4]
The import container should be able to link to any instance of a [tenforce/virtuoso](https://hub.docker.com/r/tenforce/virtuoso) image. This involves getting the libvirtodbc from it.

**Comment by TBoonX** [comment]
Do you mean instead of having 
`RUN apt-get install -y git virtuoso-opensource` inside the Dockerfile
we should use the binaries from the tenforce/virtuoso image?

**Comment by white-gecko** [comment]
`apt-get install -y git` should be ok.
But for the virtuoso we should try to link in, via a volume, the binaries from the respective virtuoso container.

**Comment by TBoonX** [comment]
I pushed a commit, please check it out and close the ticket if it fits your needs.

**Comment by white-gecko** [comment]
No it is not yet solved. The importer cannot find the virtuoso's `isql-vt` executable:

```
pfarrerbuch_import | [INFO] waiting for store to come online
pfarrerbuch_import | [ERROR] running the these commands in virtuoso:
pfarrerbuch_import | status();
pfarrerbuch_import | error code: 127
pfarrerbuch_import | output:
pfarrerbuch_import | ./import.sh: line 25: isql-vt: command not found
```

**Comment by TBoonX** [comment]
Sry I forgot to use th correct path in import.sh.
Also it seems like isql-vt is not existing in the virtuoso container. I will search if there is a replacement.

**Comment by white-gecko** [comment]
The isql-vt is in `/usr/local/virtuoso-opensource/bin/` (`/virtuoso/local/bin/` within the importer container). But we can't execute it, because it requires libreadline6, which is not available for ubuntu 18:04 anymore. I think importing all the libraries from the virtuoso container is complicated. So I tried to proceed with the unixodb isql command (https://www.mankier.com/1/isql). An instruction to use it with virtuoso is posted here: https://sourceforge.net/p/virtuoso/mailman/virtuoso-users/thread/4B117160.3020704%40webr3.org/.

But still there are some problems executing our commands.

**Comment by TBoonX** [comment]
Do you use an old version of tenforce/virtuoso? Because for me its not there, only isql-v and isql-vw.
If we need a package we could install it the same way its installed in the tenforce/virtuoso Dockerfile.

**Comment by white-gecko** [comment]
Ah yes, `isql-v` is, I think, the same as `isql-vt` it is just named differently in different versions and distributions.

**Comment by white-gecko** [comment]
Maybe we can aslo try by installing the `virtuoso-opensource` package again and seeing if the `isql-v`/`isql-vt` that is included in the package helps us to connect.

**Comment by white-gecko** [comment]
I've committed my attempts to https://github.com/Dockerizing/virtuoso-import-docker/tree/feature/tryunixodbx

**Comment by TBoonX** [comment]
In the master branch the issue of this ticket seems to be resolved.

**Comment by white-gecko** [comment]
No I still get
`/virtuoso/local/bin/isql-v: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`

I'm using `tenforce/virtuoso:1.1.0-virtuoso7.2.4` (cf. https://github.com/Dockerizing/Pfarrerbuch.compose)

**Comment by TBoonX** [comment]
You need to build the importer image again in order to have libreadline.

If the libreadline installable will change, it will also effect tenforce/virtuoso which then have to be handled in both images the same way. If we find an easy solution like with e.g. unixodb isql, then we could switch to it, but for now its working fine.

Your edge case which includes an old version of tenforce/virtuoso should be handled in a fork or branch.

**Comment by white-gecko** [comment]
But does the current solution as introduced in 26fdcc1d03c96d442d3312d57d705f473570ac29 also work for you? If so thank we have a common solution.

**Comment by TBoonX** [comment]
c07a1327ea24c56329fd60ed84932b53599d7113 (my last commit) worked.

**Comment by TBoonX** [comment]
If you want to keep the `virtuoso-opensource` installation in the importer Dockerfile, then we have to remove the volumes. They are not needed then.

**Comment by white-gecko** [comment]
I think the respective volume is removed already, isn't it?
https://github.com/Dockerizing/Pfarrerbuch.compose/blob/master/docker-compose.yml#L55-L65

**Comment by TBoonX** [comment]
I meant this repo. I will do it.
